version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - Database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=mujibai
      - POSTGRES_PASSWORD=mujibai

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  Database:
    driver: local
